//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.CARRITO = new HashSet<CARRITO>();
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }
    
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public PRODUCTO oProducto { get; set; }
        public MARCA oMarca { get; set; }
        public CATEGORIA oCategoria { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public decimal Precio { get; set; }
        public string PrecioTexto { get; set; }
        public Nullable<int> Stock { get; set; }
        public string RutaImagen { get; set; }
        public string NombreImagen { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Base64 { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual ICollection<CARRITO> CARRITO { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual MARCA MARCA { get; set; }
    }
}
