//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public VENTA()
        {
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }
    
        public int IdVenta { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public int TotalProducto { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public string Contacto { get; set; }
        public string IdDistrito { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string IdTransaccion { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public List<DETALLE_VENTA> oDetalleVenta { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
    }
}
